# Generated by Django 3.1.6 on 2022-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviseapp', '0002_auto_20220309_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
