# Generated by Django 3.1.6 on 2022-05-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviseapp', '0003_movies_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='short_description',
            field=models.TextField(max_length=50000),
        ),
    ]
