# Generated by Django 3.1.6 on 2022-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviseapp', '0004_auto_20220519_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
