# Generated by Django 3.1.6 on 2022-05-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviseapp', '0005_movies_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=3000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
